/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Martin Hara
 */
public class modul3soal2revisi extends javax.swing.JFrame {

    /**
     * Creates new form modul3soal2revisi
     */
    public modul3soal2revisi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtgaji = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtjml = new javax.swing.JTextField();
        btncek = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtjmlgaji = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtjmlkendaraan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtpajak = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("PROGRAM MENGHITUNG PAJAK");

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(new java.awt.GridLayout(6, 2, 4, 4));

        jLabel3.setText("   GAJI                :");
        jPanel4.add(jLabel3);
        jPanel4.add(txtgaji);

        jLabel1.setText("   KENDARAAN :");
        jPanel4.add(jLabel1);
        jPanel4.add(txtjml);

        btncek.setIcon(new javax.swing.ImageIcon("C:\\Users\\Martin Hara\\Downloads\\search2.png")); // NOI18N
        btncek.setText("CEK");
        btncek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncekActionPerformed(evt);
            }
        });
        jPanel4.add(btncek);

        btnreset.setIcon(new javax.swing.ImageIcon("C:\\Users\\Martin Hara\\Downloads\\Reset.png")); // NOI18N
        btnreset.setText("RESET");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        jPanel4.add(btnreset);

        jLabel4.setText("    GAJI");
        jPanel4.add(jLabel4);

        txtjmlgaji.setEditable(false);
        txtjmlgaji.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.add(txtjmlgaji);

        jLabel5.setText("   KENDARAAN :");
        jPanel4.add(jLabel5);

        txtjmlkendaraan.setEditable(false);
        txtjmlkendaraan.setBackground(new java.awt.Color(255, 255, 255));
        txtjmlkendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjmlkendaraanActionPerformed(evt);
            }
        });
        jPanel4.add(txtjmlkendaraan);

        jLabel6.setText("   PAJAK             :");
        jPanel4.add(jLabel6);

        txtpajak.setEditable(false);
        txtpajak.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.add(txtpajak);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addContainerGap(58, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncekActionPerformed
        // TODO add your handling code here:
         String fgaji = txtgaji.getText();
        int gaji = Integer.valueOf(fgaji);

        String fjml = txtjml.getText();
        int jumlahKendaraan = Integer.valueOf(fjml);

        double pajak = 0;

        if (gaji >= 10000000 && jumlahKendaraan >= 3) {
            pajak = 0.15 * gaji;
        } else if (gaji >= 5000000 && jumlahKendaraan == 2) {
            pajak = 0.10 * gaji;
        } else if (gaji >= 5000000 && jumlahKendaraan == 1) {
            pajak = 0.07 * gaji;
        } else if (gaji < 5000000 && jumlahKendaraan == 1) {
            pajak = 0.05 * gaji;
        } else if (gaji < 5000000 && jumlahKendaraan == 0) {
            pajak = 0.025 * gaji;
        }
        
        txtjmlgaji.setText(""+gaji);
        txtjmlkendaraan.setText(""+jumlahKendaraan);
        txtpajak.setText(""+pajak);
    }//GEN-LAST:event_btncekActionPerformed

    private void txtjmlkendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjmlkendaraanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjmlkendaraanActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        txtgaji.setText("");
        txtjml.setText("");
        txtjmlgaji.setText("");
        txtjmlkendaraan.setText("");
        txtpajak.setText("");
    }//GEN-LAST:event_btnresetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modul3soal2revisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modul3soal2revisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modul3soal2revisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modul3soal2revisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modul3soal2revisi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncek;
    private javax.swing.JButton btnreset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtgaji;
    private javax.swing.JTextField txtjml;
    private javax.swing.JTextField txtjmlgaji;
    private javax.swing.JTextField txtjmlkendaraan;
    private javax.swing.JTextField txtpajak;
    // End of variables declaration//GEN-END:variables
}
